# Generated by Django 4.0.1 on 2022-10-06 19:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anatomy.course_list')),
            ],
        ),
        migrations.CreateModel(
            name='Ana_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anatomy.course_list')),
            ],
            options={
                'verbose_name': 'Anatomy Quiz',
                'verbose_name_plural': 'Anatomy Quizzes',
            },
        ),
    ]
