# Generated by Django 4.0.1 on 2022-10-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ana_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anatomy.ana_quiz')),
            ],
            options={
                'verbose_name': 'Anatomy Question',
                'verbose_name_plural': 'Anatomy Questions',
            },
        ),
        migrations.CreateModel(
            name='Ana_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anatomy.ana_question')),
            ],
            options={
                'verbose_name': 'Anatomy Answer',
                'verbose_name_plural': 'Anatomy Answers',
            },
        ),
    ]
