# Generated by Django 4.0.1 on 2022-10-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0002_ana_question_ana_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_summary',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
