# Generated by Django 4.0.1 on 2022-10-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0003_course_summary_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ana_question',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='anatomy.course_list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ana_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='anatomy.ana_question'),
        ),
        migrations.AlterField(
            model_name='ana_question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='anatomy.ana_quiz'),
        ),
        migrations.AlterField(
            model_name='ana_quiz',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='anatomy.course_list'),
        ),
    ]
